from HvZ.models import *
from django.contrib import admin

admin.site.register(School)
admin.site.register(Building)
admin.site.register(BuildingKind)
admin.site.register(Dorm)
admin.site.register(Academic)
admin.site.register(Game)
admin.site.register(Rule)
admin.site.register(MissionStory)
admin.site.register(Mission)
admin.site.register(MissionPic)
admin.site.register(MissionPoint)
admin.site.register(Plot)
admin.site.register(Player)
admin.site.register(PlayerCellSetting)
admin.site.register(PlayerWebSetting)
admin.site.register(PlayerProfileSetting)
admin.site.register(Character)
admin.site.register(FeedCode)
admin.site.register(Meal)
admin.site.register(Classes)
admin.site.register(MissionAttendance)
admin.site.register(Squad)
admin.site.register(SquadMember)
admin.site.register(ForumThread)
admin.site.register(ForumPost)
admin.site.register(Award)
admin.site.register(Achievement)
admin.site.register(MealsPerHour)
admin.site.register(MealsPerBuilding)
admin.site.register(ClassAttendance)
admin.site.register(OnDuty)
