# Generated by Django 2.0.2 on 2018-02-07 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hvz.main.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(unique=True)),
            ],
            options={
                'get_latest_by': 'start_date',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_oz', models.BooleanField(default=False)),
                ('feed', hvz.main.models.FeedCodeField(max_length=16)),
                ('team', models.CharField(choices=[('H', 'Humans'), ('Z', 'Zombies')], default='H', max_length=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('grad_year', models.PositiveIntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Game')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_set', to='main.School'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meal',
            name='eaten',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eaten_set', to='main.Player'),
        ),
        migrations.AddField(
            model_name='meal',
            name='eater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_set', to='main.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('user', 'game'), ('feed', 'game')},
        ),
    ]
