# Generated by Django 2.0.2 on 2018-02-09 05:09

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('main', '0003_auto_20180209_0441'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerRole',
            new_name='Role',
        ),
    ]
