# Generated by Django 2.0.2 on 2018-02-09 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180209_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('building_type', models.CharField(choices=[('C', 'Academic'), ('T', 'Athletics'), ('D', 'Dorm'), ('I', 'Dining Hall'), ('L', 'Landmark'), ('O', 'Other')], max_length=1)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.School')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='dorm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Building'),
        ),
    ]
