# Generated by Django 2.0.2 on 2018-02-09 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180209_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Building'),
        ),
    ]
