# Generated by Django 2.0.2 on 2018-03-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_meal_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='brains',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
