# Generated by Django 2.0.2 on 2018-03-29 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_player_brains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='dorm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Building'),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Role'),
        ),
        migrations.AlterField(
            model_name='player',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_set', to='main.School'),
        ),
    ]
